### ISSUE TITLE
Pre-commit hook failed for me on Windows

### ISSUE THREAD

**Issue by MarcoGorelli** [tonybaloney/wily#110]
Here is the "wily" part of my pre-commit.yaml file:
```
-   repo: local
    hooks:
    -   id: wily
        name: wily
        entry: wily diff
        verbose: true
        language: python
        additional_dependencies: [wily]
```

If I make some code changes and then commit them, the wily check throws an error for me.

Here is my wily version:
```
>wily --version
🦊 wily, version 1.16.0
```

Here is the full traceback:

<details>
wily.....................................................................Failed
- hook id: wily
- duration: 8.73s
- exit code: 1

Using default metrics ['maintainability.mi', 'halstead.h1', 'raw.loc', 'cyclomatic.complexity']
Comparing current with 788559b by Nicholas Herriot on 2020-03-12.
Traceback (most recent call last):
  File "c:\users\m.gorelli.corp\.conda\envs\biz-plan-simulator\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\m.gorelli.corp\.conda\envs\biz-plan-simulator\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\m.gorelli.CORP\.cache\pre-commit\repohf4691sb\py_env-default\Scripts\wily.EXE\__main__.py", line 7, in <module>
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\wily\__main__.py", line 305, in diff
    revision=revision,
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\wily\commands\diff.py", line 165, in diff
    headers=headers, tabular_data=results, tablefmt=DEFAULT_GRID_STYLE
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\m.gorelli.corp\.conda\envs\biz-plan-simulator\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-127: character maps to <undefined>
Using default metrics ['maintainability.mi', 'halstead.h1', 'raw.loc', 'cyclomatic.complexity']
Comparing current with 788559b by Nicholas Herriot on 2020-03-12.
Traceback (most recent call last):
  File "c:\users\m.gorelli.corp\.conda\envs\biz-plan-simulator\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\m.gorelli.corp\.conda\envs\biz-plan-simulator\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\m.gorelli.CORP\.cache\pre-commit\repohf4691sb\py_env-default\Scripts\wily.EXE\__main__.py", line 7, in <module>
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\click\decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\wily\__main__.py", line 305, in diff
    revision=revision,
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\wily\commands\diff.py", line 165, in diff
    headers=headers, tabular_data=results, tablefmt=DEFAULT_GRID_STYLE
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\users\m.gorelli.corp\.cache\pre-commit\repohf4691sb\py_env-default\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\users\m.gorelli.corp\.conda\envs\biz-plan-simulator\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-132: character maps to <undefined>
</details>

**Comment by cbetylkata** [comment]
@MarcoGorelli  I bumped into the same issue and was wondering if you managed to find a solution or workaround to it ?

**Comment by MarcoGorelli** [comment]
I stopped using Windows :flushed:
