### ISSUE TITLE
Ignore Folders

### ISSUE THREAD

**Issue by std-dev-bit** [tonybaloney/wily#111]
I installed wily in a virtualenv and it interferes with the .venv folder. Is there a way to ignore folders or something to include in wily.cfg?

$ python3 -m venv .venv
$ . .venv/bin/activate

(.venv) [root@src Library]# wily build code/
Traceback (most recent call last):
  File "/src/Library/.venv/bin/wily", line 11, in <module>
    sys.exit(cli())
  File "/src/Library/.venv/lib64/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/src/Library/.venv/lib64/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/src/Library/.venv/lib64/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/src/Library/.venv/lib64/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/src/Library/.venv/lib64/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/src/Library/.venv/lib64/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/src/Library/.venv/lib64/python3.6/site-packages/wily/__main__.py", line 133, in build
    operators=resolve_operators(config.operators),
  File "/src/Library/.venv/lib64/python3.6/site-packages/wily/operators/__init__.py", line 153, in resolve_operators
    return [resolve_operator(operator) for operator in iter(operators)]
  File "/src/Library/.venv/lib64/python3.6/site-packages/wily/operators/__init__.py", line 153, in <listcomp>
    return [resolve_operator(operator) for operator in iter(operators)]
  File "/src/Library/.venv/lib64/python3.6/site-packages/wily/operators/__init__.py", line 141, in resolve_operator
    raise ValueError(f"Operator {name} not recognised.")
ValueError: Operator c not recognised.

**Comment by std-dev-bit** [comment]
Also see additional tries:

# python3 -m wily build code/
Oh no, Wily crashed! See /tmp/tmptqay6pcqwily_log for information.
If you think this crash was unexpected, please raise an issue at https://github.com/tonybaloney/wily/issues and copy the log file into the issue report along with some information on what you were doing.

# python3 -m wily setup
Could not locate wily cache, the cache is required to provide insights.
Do you want to run setup and index your project now? [y/N]y
How many previous git revisions do you want to index? : 10
Path to your source files; comma-separated for multiple: /src/Library/code

Oh no, Wily crashed! See /tmp/tmp8ou1crslwily_log for information.
If you think this crash was unexpected, please raise an issue at https://github.com/tonybaloney/wily/issues and copy the log file into the issue report along with some information on what you were doing.

# cat /tmp/tmp8ou1crslwily_log
Could not locate wily cache, the cache is required to provide insights.
Oh no, Wily crashed! See /tmp/tmp8ou1crslwily_log for information.
If you think this crash was unexpected, please raise an issue at https://github.com/tonybaloney/wily/issues and copy the log file into the issue report along with some information on what you were doing.

**Comment by DahlitzFlorian** [comment]
I ran your example both on Python 3.7 and 3.8 and was not able to reproduce it. Furthermore, I used a global installed wily version (latest) and one installed in the newly created virtual environment. Again, I was not able to reproduce it.
