### ISSUE TITLE
wily's temp files seem to sometimes conflict with git checkout

### ISSUE THREAD

**Issue by brad-engel** [tonybaloney/wily#135]
**Describe the bug**
wily build crashes every time it checks out a specific commit in my history with message "Updating the following directories would lose untracked files in them". Before running wily there were no untracked files, and after this crash the only untracked files in my git / code directory were the ones placed there by wily.

**To Reproduce**
I'm not sure how to recreate the conditions, but this happens every time wily build hits a specific commit in my project's history. I'm not sure what is special about that commit.

**Expected behavior**
wily build completes without crashing

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 11.3
 - Browser N/A

**Additional context**
There were no untracked files in this directory before I ran wily. The only untracked files after this crash were wily temporary files within my git code directory. Note that adding these wily files to my .gitignore does not change the crash.

  cmdline: git checkout 8db258e807690ad7b48fdca1d1f9a08daa178f78
  stderr: 'error: Updating the following directories would lose untracked files in them:
	mycode

Aborting''
Traceback (most recent call last):
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/bin/wily", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/wily/__main__.py", line 133, in build
    build(
  File "/usr/local/lib/python3.9/site-packages/wily/commands/build.py", line 209, in build
    raise e
  File "/usr/local/lib/python3.9/site-packages/wily/commands/build.py", line 110, in build
    archiver.checkout(revision, config.checkout_options)
  File "/usr/local/lib/python3.9/site-packages/wily/archivers/git.py", line 102, in checkout
    self.repo.git.checkout(rev)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 1011, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/lib/python3.9/site-packages/git/cmd.py", line 828, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git checkout 8db258e807690ad7b48fdca1d1f9a08daa178f78
  stderr: 'error: Updating the following directories would lose untracked files in them:
	mycode

**Comment by tonybaloney** [comment]
Which files did it create? The wily cache should go into `$HOME/.wily/HASH`

Can you run the commands again with the `--debug` flags and share the output
