### ISSUE TITLE
Wily fails to build cache

### ISSUE THREAD

**Issue by jugmac00** [tonybaloney/wily#36]
- Python 3.6.6 on Ubuntu as a WSL on Windows 10
- wily==1.8.0 (btw would be nice to see version number when using "wily" or "wily help"
- fairly big project
- after like 10-15 minutes I receive the following output

```(wily) jugmac00@DESKTOP-jugmac00:/mnt/d/Projects/bliss_deployment/work/zope/checkout/bliss.git$ wily build BlissProducts/ GeneralProducts/ Products/
Found 50 revisions from 'git' archiver in '/mnt/d/Projects/bliss_deployment/work/zope/checkout/bliss.git'.
Running operators - raw,cyclomatic,maintainability


Failed to build cache: ''
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/wily/commands/build.py", line 24, in run_operator
    return operator.name, instance.run(revision, config)
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/wily/operators/cyclomatic.py", line 81, in run
    raise TypeError
TypeError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/Projects/envs/wily/bin/wily", line 11, in <module>
    sys.exit(cli())
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/wily/__main__.py", line 123, in build
    operators=resolve_operators(config.operators),
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/wily/commands/build.py", line 125, in build
    raise e
  File "/mnt/d/Projects/envs/wily/lib/python3.6/site-packages/wily/commands/build.py", line 84, in build
    [(operator, revision, config) for operator in operators],
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 296, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
TypeError```

**Comment by jugmac00** [comment]
The above project is not open source, but I get the same error with e.g.
https://github.com/jugmac00/zope.viewlet
using 50 git revisions.

I would love to get a tip on how to debug this myself. How would I install wily so I can use pdb?

pip install -e does not work as wily has no setup.py.

```
/mnt/d/Projects/wily$ pip install -e .
Directory '.' is not installable. File 'setup.py' not found.
```

**Comment by tonybaloney** [comment]
Yikes! Never seen that before. I did put a TypeError into an if block for when the radon harvester returned a type that wily isn’t built for. 
I’d guess that is what’s happened. 
If you want to debug this, setup your virtual environment and install flit from pip and run “flit install”

**Comment by tonybaloney** [comment]
Here's the full trace

```
Received unexpected <class 'str'> from radon.
Failed to build cache: ''
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 47, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "/Users/anthonyshaw/repo/wily/wily/commands/build.py", line 24, in run_operator
    return operator.name, instance.run(revision, config)
  File "/Users/anthonyshaw/repo/wily/wily/operators/cyclomatic.py", line 82, in run
    raise TypeError
TypeError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/anthonyshaw/repo/wily/wily/__main__.py", line 319, in <module>
    cli()  # pragma: no cover
  File "/Users/anthonyshaw/repo/wily/.venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anthonyshaw/repo/wily/.venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/anthonyshaw/repo/wily/.venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anthonyshaw/repo/wily/.venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anthonyshaw/repo/wily/.venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/anthonyshaw/repo/wily/.venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anthonyshaw/repo/wily/wily/__main__.py", line 123, in build
    operators=resolve_operators(config.operators),
  File "/Users/anthonyshaw/repo/wily/wily/commands/build.py", line 125, in build
    raise e
  File "/Users/anthonyshaw/repo/wily/wily/commands/build.py", line 84, in build
    [(operator, revision, config) for operator in operators],
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError
```

**Comment by tonybaloney** [comment]
That value is just the word "error" in a string! I would assume that's coming from Radon and there's more context somewhere why it's happening.

**Comment by tonybaloney** [comment]
This seems to be some sort of special value to radon internally https://github.com/rubik/radon/blob/master/radon/cli/harvest.py#L155

**Comment by tonybaloney** [comment]
It fails always on the same commit hash too https://github.com/jugmac00/zope.viewlet/commit/75af3aaf0402223afec9972a55eb1592af189cde

wily needs a fallback mechanism for unparseable commits to skip them. I'll raise another issue.

in the meantime @jugmac00 you can limit the number of commits with the `-n` flag in the build command to, say 10 and it'll give you the stats before this commit

**Comment by jugmac00** [comment]
If you have to be this tall, to write multithreaded code, how tall do you have to be to debug it? :-)

I utterly failed at setting a successful breakpoint.

Uhm ...
 `  File "/usr/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
"""
`

cf https://bholley.net/blog/2015/must-be-this-tall-to-write-multi-threaded-code.html

**Comment by tonybaloney** [comment]
Pro-tip - use this debugger instead :-) https://pypi.org/project/web-pdb/ I put the breakpoint on the line before the `raise TypeError` in operators/cyclomatic.py

**Comment by tonybaloney** [comment]
Found the issue and fixed in #39 , curiously this line was causing it to freak out. That's invalid syntax AFAIK but it should handle it gracefully, which it does now
https://github.com/jugmac00/zope.viewlet/blob/75af3aaf0402223afec9972a55eb1592af189cde/src/zope/viewlet/manager.py#L146

**Comment by tonybaloney** [comment]
Something else really important, it took me about 40 seconds to build on that project. Please make sure you're not providing the project root as the target, because it'll build things like your entire venv if its in the same directory.

**Comment by tonybaloney** [comment]
@jugmac00 fixed in 1.8.1 please can you confirm it works on your other project. It'll tell you in the output which line failed to process

**Comment by jugmac00** [comment]
@tonybaloney - thank you very much for your effort.

I really love my pdb++, but Web-PDB looks very nice, and at least it did not crash in this multi(threaded|processed) scope- well at least not for the "TypeError" :-)

Running wily 1.8.1 revealed
- a bunch of mixed tabs and spaces issues
- tons of invalid syntax (usage of the old exception syntax, the one with the comma)
on my legacy project.

I can't yet use a linter as ... uhm.. some nasty code generator is involved which is pretty easily offended :-)

Ok, so far so good - but at the end, the build crashes again. But with a different error. I do not know if you want to have this ticket or in a new one... But here we go:

```Traceback (most recent call last):
  File "/mnt/d/Projects/envs/wily-editable/bin/wily", line 11, in <module>
    sys.exit(cli())
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/wily/__main__.py", line 293, in setup
    handle_no_cache(ctx)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/wily/__main__.py", line 314, in handle_no_cache
    skip_gitignore_check=False,
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/wily/__main__.py", line 123, in build
    operators=resolve_operators(config.operators),
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/wily/commands/build.py", line 127, in build
    raise e
  File "/mnt/d/Projects/envs/wily-editable/lib/python3.6/site-packages/wily/commands/build.py", line 116, in build
    result[str(root)][metric.name] = func(values)
  File "/usr/lib/python3.6/statistics.py", line 507, in mode
    'no unique mode; found %d equally common values' % len(table)
statistics.StatisticsError: no unique mode; found 2 equally common values```

Looks like mode is called on a list with more than one winner.

I tried to quickly "web-pdb" into the issue, but web pdb failed me this time - I just got an empty web pdb screen.

That's for now - maybe I'll have a look at it laters.

P.S.: This time the builtin pdb works oO

![wsl](https://user-images.githubusercontent.com/9895620/50220391-81d77380-0392-11e9-9037-9da354ab24a3.png)

**Comment by tonybaloney** [comment]
I forgot about statistics error on the mode function. all of the tests I've been doing have lots of data. OK, so if you do

```
import statistics
statistics.mode(['A', 'B'])
```

You'll see the error 

there are better functions for this, but a custom one would probably be a better choice. Basically each metric declares how to aggregate it's values for a directory. Some values (Lines of Code) it should be sum, some (like MI) should be average. This rank is a discrete value so I thought mode would make sense

**Comment by tonybaloney** [comment]
Fixing in #43 for now you can skip it by building with `-o raw,cyclomatic` and skip the maintainability metrics

**Comment by jugmac00** [comment]
Thank you - wily is now completing the run.

P.S.: Hard to contribute if you fix all the bugs - almost instantly! :-)

**Comment by tonybaloney** [comment]
@s0m01cp that's a unique issue, please could you raise a bug with some details on the environment and factors leading to the issue
