### ISSUE TITLE
TypeError: build() got an unexpected keyword argument 'skip_gitignore_check'

### ISSUE THREAD

**Issue by colinalexander** [tonybaloney/wily#61]
When running the initial set-up for a relatively new repo (just 5 commits), I get the following error below (note that my repo does have a `.gitignore` file).  

It appears that line 355 in `wily/__main__.py` calls a functions with `skip_gitignore_check=False`, but that argument is not recognized within the context.

```Traceback (most recent call last):
  File "/usr/local/miniconda/envs/my_org/bin/wily", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/wily/__main__.py", line 334, in setup
    handle_no_cache(ctx)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/wily/__main__.py", line 355, in handle_no_cache
    skip_gitignore_check=False,
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/miniconda/envs/my_org/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
TypeError: build() got an unexpected keyword argument 'skip_gitignore_check'```

**Comment by tonybaloney** [comment]
Thanks for raising, did you follow the prompts on the first pass? There’s a kwarg on the line you mentioned which shouldn’t be there.

**Comment by tonybaloney** [comment]
As a temporary workaround, try running the build command on the CLI with all the arguments instead of using the fallback prompt.
