### ISSUE TITLE
Wily diff output

### ISSUE THREAD

**Issue by cometchaser** [tonybaloney/wily#65]
Hi,

I wanted to use wily as an external tool in Pycharm, in order to see the wily diff of a file.
`wily.exe diff foobar.py`
However this fails and I get this message:

`
...
File "c:\programdata\anaconda3\envs\foobar\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-123: character maps to <undefined>`

Same happens in the cmd when I wants to pipe the output to a file.
`wily.exe diff foobar.py > wilydiff.txt`

The output options are not valid for the diffs.
Any idea? Thanks

**Comment by tonybaloney** [comment]
Yikes!

What version of Python is this and what version of Wily do you have installed?

Please can you run `wily index` and share some of the output

**Comment by cometchaser** [comment]
Here see the conda environment file:
[wilyenv.txt](https://github.com/tonybaloney/wily/files/3008922/wilyenv.txt)

and the index gives:
`$wily index
--------Configuration---------
Path: D:\Projects\foobar
Archiver: git
Operators: {'halstead', 'maintainability', 'cyclomatic', 'raw'}

-----------History------------
╒════════════╤═══════════════════════════════════╤════════════╕
│ Revision   │ Author                            │ Date       │
╞════════════╪═══════════════════════════════════╪════════════╡
│ 6a0dcb9    │ CometChaser                       │ 2019-03-22 │
├────────────┼───────────────────────────────────┼────────────┤
`
... and so on ...

I also add some more output from the `wily diff`:
`$ wily.exe diff foobar.py > test.txt

Using default metrics ['cyclomatic.complexity', 'maintainability.mi', 'raw.loc', 'halstead.h1']
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\foobar\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\foobar\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\foobar\Scripts\wily.exe\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\wily\__main__.py", line 245, in diff
    config=config, files=files, metrics=metrics, changes_only=not all, detail=detail
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\wily\commands\diff.py", line 130, in diff
    headers=headers, tabular_data=results, tablefmt=DEFAULT_GRID_STYLE
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "c:\programdata\anaconda3\envs\foobar\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "c:\programdata\anaconda3\envs\foobar\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-145: character maps to <undefined>
`

**Comment by GabdaZM** [comment]
I have a similar problem, but with almost every command (build command works):
[wily-err-log.txt](https://github.com/tonybaloney/wily/files/3038075/wily-err-log.txt)

**Comment by tonybaloney** [comment]
@GabdaZM are you also using anaconda? I think this is related to the default encoding profiles in the environment.

**Comment by GabdaZM** [comment]
No, I am using PyCharm on wndows, and using UTF-8 encoding, LF line ending.

**Comment by cbetylkata** [comment]
I am having the same issue when I tried using the pre-commit hook. Also using PyCharm on Windowns 10 with UTF-8 encoding and LF as line separator.
`wily, version 1.19.0`

Has there been any resolution or possible workaround for this issue?
