### ISSUE TITLE
pre-commit hook is broken in 1.12.2

### ISSUE THREAD

**Issue by tonybaloney** [tonybaloney/wily#67]
Because of the dynamic cache folders, the pre-commit hook will execute from a different directory and not detect the cache folder of the root path

```
➜  notations git:(master) ✗ git commit -m "add while test"
wily.....................................................................Failed
hookid: wily

Using default metrics []
Traceback (most recent call last):
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/bin/wily", line 11, in <module>
    sys.exit(cli())
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/wily/__main__.py", line 202, in diff
    config=config, files=files, metrics=metrics, changes_only=not all, detail=detail
  File "/Users/anthonyshaw/.cache/pre-commit/repo9vvhlva6/py_env-python3.6/lib/python3.6/site-packages/wily/commands/diff.py", line 35, in diff
    raise RuntimeError("Missing index, run `wily build`.")
RuntimeError: Missing index, run `wily build`.

```

**Comment by webknjaz** [comment]
So with
```yaml
---

repos:
- repo: https://github.com/tonybaloney/wily.git
  rev: 1.25.0
  hooks:
  - id: wily
    entry: wily --debug diff

...
```
_(the hook definition is quite old, and I had to override just `wily` for testing, it should probably be fixed upstream to correspond to what's in the pre-commit config file anyway)_
and
```console
$ python -m pip show pre-commit
Name: pre-commit
Version: 3.5.0
Summary: A framework for managing and maintaining multi-language pre-commit hooks.
Home-page: https://github.com/pre-commit/pre-commit
Author: Anthony Sottile
Author-email: asottile@umich.edu
License: MIT
Location: ~/.pyenv/versions/venv-pyenv-py3.11.5/lib/python3.11/site-packages
Requires: cfgv, identify, nodeenv, pyyaml, virtualenv
Required-by:
```
it doesn't traceback like in the above excerpt.

Instead, it attempts to interactively ask for the cache initialization, having not detected usable stdin:
```console
$ git commit
wily.....................................................................Failed
- hook id: wily
- exit code: 1

Could not locate wily.cfg, using default config.
Fixing path to /absolute/project/src/path
Loaded configuration from wily.cfg
Capturing logs to /tmp/tmp5n69lwoiwily_log
Generating cache for /absolute/project/src/path
path=PosixPath('/absolute/project/src/path') sha='b6f1bbefe' HOME=PosixPath('~') cache_path='~/.wily/b6f1bbefe'
Cache path is ~/.wily/b6f1bbefe
Could not locate wily cache, the cache is required to provide insights.
Do you want to run setup and index your project now? [y/N]
Aborted!
```
_(that one line starting with `path=` is a `print()` I injected after https://github.com/tonybaloney/wily/blob/2590691/src/wily/helper/__init__.py#L54 in the pre-commit managed virtualenv, before I noticed `--debug`)_

When the entrypoint is patched as follows
```diff
 ---

 repos:
 - repo: https://github.com/tonybaloney/wily.git
   rev: 1.25.0
   hooks:
   - id: wily
-    entry: wily --debug diff
+    entry: >
+      bash -c '
+      {
+        echo y;
+        echo 1;
+        echo ${@: 0}
+      }
+      | wily --debug diff ${@: 0}
+      '

 ...
```
the crash looks like this:
```console
$ git commit
wily.....................................................................Failed
- hook id: wily
- exit code: 1

Could not locate wily.cfg, using default config.
Fixing path to /absolute/project/src/path
Loaded configuration from wily.cfg
Capturing logs to /tmp/tmpikg37jmkwily_log
Generating cache for /absolute/project/src/path
path=PosixPath('/absolute/project/src/path') sha='b6f1bbefe' HOME=PosixPath('~') cache_path='~/.wily/b6f1bbefe'
Cache path is ~/.wily/b6f1bbefe
Could not locate wily cache, the cache is required to provide insights.
Do you want to run setup and index your project now? [y/N]How many previous git revisions do you want to index? : Path to your source files; comma-separated for multiple: Fixing revisions to 1
Fixing archiver to git
Fixing targets to ['smth.py smth2.py']
Using git archiver module
Failed to setup archiver: 'Dirty repository, make sure you commit/stash files first'
```

So I conclude that there's still problems with using `wily` under `pre-commit`, but they are different from the original traceback. This could probably be addressed with:
1) an extra CLI flag, a-la `--yes`, for unconditional non-interactive cache initialization;
2) deriving the number of commits from `--revision=HEAD^` (tried this, it still asks that second prompt, haven't looked into why);
3) properly bypassing the positional CLI arguments (they seem to be lost, hence the third prompt);
4) allowing the custom archiver to be set, maybe? The lack of the CLI option stopped me from trying out what would happen with the filesystem archiver;
5) maybe, a CLI flag for allowing dirty Git in this context?
